// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Appbackup: typeof import('./src/components/appbackup.vue')['default']
    ArgumentInput: typeof import('./src/components/argument-input.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Proposition: typeof import('./src/components/proposition.vue')['default']
    PropositionInput: typeof import('./src/components/proposition-input.vue')['default']
    Stage: typeof import('./src/components/stage.vue')['default']
    TheForm: typeof import('./src/components/the-form.vue')['default']
  }
}

export {}
