// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    All: typeof import('./src/components/all.vue')['default']
    Appbackup: typeof import('./src/components/appbackup.vue')['default']
    Argument: typeof import('./src/components/argument.vue')['default']
    ArgumentInput: typeof import('./src/components/argument-input.vue')['default']
    ArgumentShow: typeof import('./src/components/argument-show.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Form: typeof import('./src/components/form.vue')['default']
    Layout: typeof import('./src/components/layout.vue')['default']
    Proposition: typeof import('./src/components/proposition.vue')['default']
    PropositionInput: typeof import('./src/components/proposition-input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stage: typeof import('./src/components/stage.vue')['default']
    Syllogism: typeof import('./src/components/Syllogism.vue')['default']
    TheForm: typeof import('./src/components/the-form.vue')['default']
    TheStage: typeof import('./src/components/the-stage.vue')['default']
  }
}

export {}
